function resetDatabase end
function resetInfectiousStatusesOutbreaksAndExposures end
function resetInfectiousStatusesOutbreaksAndExposuresAndReprocessPatientData end
function importExistingConfirmedStatuses end
function confirmCarriersAndSuspicionsAndIsolate end
