include("sampleMaterialTypeConversionDict.jl")

function importStays end
function importAnalyses end
function checkIfNotAtRiskAnymore end
function convertETLInputDataToRequestAndResultType end
function convertETLInputDataToSampleMaterialType end
function getBasicInformationAboutAnalysesInputFile end
function getBasicInformationAboutStaysInputFile end
function getSummaryOfPendingInputFiles end
