function importStays end
function importAnalyses end
function checkIfNotAtRiskAnymore end
function convertStringInInputFileToANALYSIS_REQUEST_TYPE end
function convertStringInInputFileToANALYSIS_RESULT_VALUE_TYPE end
