function rmAccentsAndLowercase end
function cleanStringForEncryptedValueCp end
function normalizeWhites end
function removeDoubleSpaces end
function removeDoubleLineReturns end
function htmlToPlainText end
