function decryptFile end
function encryptFile end
function downloadAndProcessFile end
function extractKdfChildKeyRefFromSidecarFile end
function getKdfChildKey end
function getS3PresignedUploadUrlAndKdfChildKey end
