"""
    processDecryptedXmlFile(
        decryptedXmlFilePath::String,
        encryptionStr::String,
        dbconn::LibPQ.Connection,
    )

Run the ETL pipeline against a decrypted FHIR XML file:
1. Parse analyses and stays from the XML into DataFrames.
2. Import the analyses DataFrame.
3. Import the stays DataFrame.
4. Trigger downstream processing of the newly integrated data
   (`ETLCtrl.processNewlyIntegratedData`) so that any infectious
   statuses or contact exposures generated by the new data are
   materialised.

`encryptionStr` is the user-supplied passphrase used to decrypt patient
records stored encrypted in the database. It is forwarded unchanged to
`ETLCtrl.importAnalysesDF` and `ETLCtrl.importStaysDF`.
"""
function FileExchangeCtrl.processDecryptedXmlFile(
    decryptedXmlFilePath::String,
    encryptionStr::String,
    dbconn::LibPQ.Connection,
)

    dfOfAnalyses = ETLCtrl.FHIR.parseXMLToAnalysesDF(decryptedXmlFilePath)
    ETLCtrl.importAnalysesDF(dfOfAnalyses, encryptionStr)

    dfOfStays = ETLCtrl.FHIR.parseXMLToStaysDF(decryptedXmlFilePath)
    ETLCtrl.importStaysDF(dfOfStays, encryptionStr)

    ETLCtrl.processNewlyIntegratedData(dbconn)

    return nothing

end
