"""
    processDecryptedXmlFile(
        decryptedXmlFilePath::String,
        encryptionStr::String,
        dbconn::LibPQ.Connection,
        ;alsoProcessNewlyIntegratedData::Bool,
    )

Run the ETL pipeline against a decrypted FHIR XML file:
1. Parse analyses and stays from the XML into DataFrames.
2. Import the analyses DataFrame.
3. Import the stays DataFrame.
4. If `alsoProcessNewlyIntegratedData` is `true`, trigger downstream
   processing of the newly integrated data
   (`ETLCtrl.processNewlyIntegratedData`) so that any infectious
   statuses or contact exposures generated by the new data are
   materialised. When it is `false`, the import is performed but the
   downstream processing step is skipped — useful for callers that
   want to batch several imports before triggering the (relatively
   expensive) post-processing step.

`encryptionStr` is the user-supplied passphrase used to decrypt patient
records stored encrypted in the database. It is forwarded unchanged to
`ETLCtrl.importAnalysesDF` and `ETLCtrl.importStaysDF`.
"""
function FileExchangeCtrl.processDecryptedXmlFile(
    decryptedXmlFilePath::String,
    encryptionStr::String,
    dbconn::LibPQ.Connection,
    ;alsoProcessNewlyIntegratedData::Bool,
)

    dfOfAnalyses = ETLCtrl.FHIR.parseXMLToAnalysesDF(decryptedXmlFilePath)
    ETLCtrl.importAnalysesDF(dfOfAnalyses, encryptionStr)

    dfOfStays = ETLCtrl.FHIR.parseXMLToStaysDF(decryptedXmlFilePath)
    ETLCtrl.importStaysDF(dfOfStays, encryptionStr)

    if alsoProcessNewlyIntegratedData
        ETLCtrl.processNewlyIntegratedData(dbconn)
    end

    return nothing

end
