include("createDummyPatient.jl")
include("deleteDummyPatient.jl")
include("createDummyUnits.jl")
include("createDummyCarrierInfectiousStatus.jl")
include("createDummyStays.jl")
include("createDummyHistoryOfACarrierPatient.jl")
include("getDefaultMasterKeyWords.jl")
