abstract type IOutbreakUnitAsso <: IEntity end
abstract type IAnalysisResult <: IEntity end
abstract type IPatientRefCrypt <: IEntity end
abstract type IInfectiousStatus <: IEntity end
abstract type IPatientBirthdateCrypt <: IEntity end
abstract type IOutbreak <: IEntity end
abstract type IPatientCurrentStatus <: IEntity end
abstract type IStay <: IEntity end
abstract type IContactExposure <: IEntity end
abstract type IOutbreakInfectiousStatusAsso <: IEntity end
abstract type IEventRequiringAttention <: IEntity end
abstract type IAnalysisRefCrypt <: IEntity end
abstract type IPatient <: IEntity end
abstract type IPatientNameCrypt <: IEntity end
abstract type IAnalysisRequest <: IEntity end
abstract type IUnit <: IEntity end
abstract type IModification <: IEntity end
abstract type IFrontendVersion <: IEntity end
abstract type IRole <: IEntity end
abstract type IAppuserRoleAsso <: IEntity end
abstract type IAppuser <: IEntity end
abstract type IRoleRoleAsso <: IEntity end
