function loadConf end
function hasConf end
function getConf end
function openDBConn end
function openDBConnAndBeginTransaction end
function beginDBTransaction end
function commitDBTransaction end
function rollbackDBTransaction end
function closeDBConn end
function getInstanceCodeName end
function getCryptPwdHttpHeaderKey end
function convertStringToZonedDateTime end
function createPartitionPatientRefIfNotExist end
function createPartitionPatientBirthdateIfNotExist end
function createPartitionPatientNameIfNotExist end
function createPartitionAnalysisRefIfNotExist end
function createPartitionStayIfNotExist end
function createPartitionAnalysisIfNotExist end
function getTablePartitionNameOnYearMonth end
function createTablePartitionOnYearMonth end
function createTablePartitionsOnYearMonthForGivenYear end
function createTablesPartitionsOnYearMonthForLastYears end
function blindBakeIsRequired end
function listEnums end

function rmAccentsAndLowercase end
function cleanStringForEncryptedValueCp end
function normalizeWhites end
function removeDoubleSpaces end
function removeDoubleLineReturns end
function formatExceptionAndStackTrace end
function formatExceptionAndStackTraceCore end
function getTimezone end
function getTimezoneAsStr end
function string2enum end

function generateHumanReadableUniqueRef end
function retrieveSequenceNextval end

function initialize_http_response_status_code end
function getCurrentFrontendVersion end
function json2Entity end

function extractCryptPwdFromHTTPRequest end
