[default]
instance_code_name=traquer_demo
data_dir=/home/traquer/DATA/
frontend_url=http://localhost:4200
blind_bake=false
timezone=Europe/Paris
unit_language_code=fra
team_email_address=monitor@yourteam.com

[custom]
module_name=Demo

[rules_parameters]
carrier_waiting_period_in_months=6
minimum_number_of_hours_for_contact_status_creation=4
rollback_for_hospitalizations_at_risk_of_carrier_in_months=6
number_of_negative_tests_for_carrier_exclusion=2
number_of_negative_tests_for_contact_exclusion=2

[admin]
admin_email=admin@yourteam.com
bcc_admin_for_every_email=true

[security]
jwt_signing_keys_uri=file:///home/traquer/jwt_signing_keys.json

[database]
host=traquer-postgresql-16-server
port=5432
database=traquer_dev
user=traquer_dev
password=traquer_dev
user_readonly=traquer_readonly
host_for_dump=traquer-postgresql-16-server
port_for_dump=5432

[email]
userid=xxxxxxx
from_address=noreply@yourteam.com
userpwd=xxxxxxx
smtpserver=xxxxxxxxxx.com:587
noemail=true
testing_mode_prefix_in_subject=true
nb_seconds_before_sending_message=10

[debug]
include_carriers_that_are_not_hospitalized=false # should be false by default
