function persist! end
function update! end
function updateVectorProps! end
function prePersist! end
function preUpdate! end
function postPersist! end
function postUpdate! end
function retrieveOneEntity end
function retrieveEntities end
function enrichWithVectorProps! end
