function getOutbreakFromEventRequiringAttention end
function initializeOutbreak end
function generateDefaultOutbreakUnitAssos end
function getOutbreaksThatCanBeAssociated end
function getOutbreakUnitAssosFromInfectiousStatus end
