include("getOutbreakFromEventRequiringAttention.jl")
include("initializeOutbreak.jl")
include("generateDefaultOutbreakUnitAssos.jl")
include("getOutbreaksThatCanBeAssociated.jl")
include("getOutbreakUnitAssosFromInfectiousStatus.jl")
