include("getOutbreakFromEventRequiringAttention.jl")
include("initializeOutbreak.jl")
include("generateDefaultOutbreakUnitAssos_DEPRECATED.jl")
include("getOutbreaksThatCanBeAssociated.jl")
include("getOutbreakUnitAssosFromInfectiousStatus.jl")
