api_routes  = ()
include("hello-world.jl")
include("appuser-api.jl")
include("analysis-api.jl")
include("analysis-request-api.jl")
include("contact-exposure-api.jl")
include("enum-api.jl")
include("event-requiring-attention-api.jl")
include("exposed-function-api.jl")
include("infectious-status-api.jl")
include("misc-api.jl")
include("outbreak-api.jl")
include("outbreak-unit-asso-api.jl")
include("patient-api.jl")
include("role-api.jl")
include("stay-api.jl")
include("task-waiting-for-user-execution-api.jl")
include("unit-api.jl")
