function getCarrierWaitingPeriod end
function getNumberOfNegativeTestsForCarrierExclusion end
function getMinimumNumberOfHoursForContactStatusCreation end
function getNumberOfNegativeTestsForContactExclusion end
