# Definitions for ETLCtrl.ScopeCtrl.
function buildStayMonitoringScopeList end
function buildStayExtractionScope end
function createStayMonitoringScopeListIfNotExist end
function createStayExtractionScope end
function getActiveStayMonitoringScopes end
function getStayExtractionScopeDTOsForExtraction end
function getStayMonitoringScopeDTOs end
function prepareStayExtractionScopeDTO end
function prepareStayMonitoringScopeDTO end
function mergeStayExtractionScopeDTOs end
function mergeStayMonitoringScopeDTOs end
function refreshStayMonitoringScopes end
