# Implementations for ETLCtrl.ScopeCtrl.
include("buildStayMonitoringScopeList.jl")
include("buildStayExtractionScope.jl")
include("createStayMonitoringScopeListIfNotExist.jl")
include("getActiveStayMonitoringScopes.jl")
include("getStayExtractionScopeDTOsForExtraction.jl")
include("createStayExtractionScope.jl")
include("prepareStayExtractionScopeDTO.jl")
include("mergeStayExtractionScopeDTOs.jl")
include("refreshStayMonitoringScopes.jl")
