function upsert! end
function createNewStayEventIfPatientAtRisk end
function createAnalysisDoneEventIfNeeded end
function createAnalysisLateEvent end
function createEventsTransferToAnotherCareFacility end
