include("upsert.jl")
include("createNewStayEventIfPatientAtRisk.jl")
include("createAnalysisDoneEventIfNeeded.jl")
include("createAnalysisLateEvent.jl")
include("createEventsTransferToAnotherCareFacility.jl")
